### ISSUE TITLE
Filename Truncation

### ISSUE THREAD

**Issue by dettrick** [LiaungYip/kooltou#1]
There appears to be an error where emails wont save if the subject line of the email makes the subsequent filename too long for the OS to handle. This is more apparent when your emails are organized into multiple nested folders, so if you have used the program it might pay to do a double check in folders that are multiple levels deep to ensure that you emails are indeed backed up.

**Comment by LiaungYip** [comment]
Fixed in new release v0.0.6. Test it and let me know if it solves the problem.
